
SCRIPTS=$(realpath $(dirname $(readlink -f ~/.zshrc))/..)

export CODE=$(realpath $(dirname $SCRIPTS))

source $CODE/Scripts/zsh/omz-config.sh

source $ZSH/oh-my-zsh.sh

source $CODE/Scripts/zsh/user-config.sh

if [ -r $HOME/.zshrc.spec ]; then
    source $HOME/.zshrc.spec
fi
